version: '2'
services:
    review_comparison-app:
        image: review_comparison
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://review_comparison-mysql:3306/review_comparison?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    review_comparison-mysql:
        extends:
            file: mysql.yml
            service: review_comparison-mysql
